version: 2.1

executors:
  docker: # Docker using the Base Convenience Image
    docker:
      - image: cimg/base:stable
  macos: # macOS executor running Xcode
    macos:
      xcode: 14.2.0

jobs:
  test:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - checkout
      - run:
          command: |
            git clone https://github.com/asdf-vm/asdf.git asdf
            . asdf/asdf.sh
            asdf plugin test lein $CIRCLE_WORKING_DIRECTORY 'lein --version'

workflows:
  test-plugin:
    jobs:
      - test:
          matrix:
            parameters:
              os: [docker, macos]
